info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
server:
  port: 8083


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empleados?verifyServerCertificate=false&useSSL=false
    username: root
    password: saam1234
  jpa:
    hibernate:
      ddl-auto: update